# Generated by Django 5.2.6 on 2025-12-03 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_registeredprofessional_terms_accepted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='professional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='content.registeredprofessional'),
        ),
    ]
