# Generated by Django 5.2.6 on 2025-09-10 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('lang_code', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('lang_name_english', models.CharField(max_length=64)),
                ('lang_name_native', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'languages',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_code', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('display_order', models.IntegerField(unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'questions',
            },
        ),
        migrations.CreateModel(
            name='RedFlag',
            fields=[
                ('red_flag_code', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('education_url_slug', models.CharField(max_length=191, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'red_flags',
            },
        ),
        migrations.CreateModel(
            name='RegisteredProfessional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('PEDIATRICIAN', 'Pediatrician'), ('CAREGIVER', 'Caregiver')], max_length=20)),
                ('salutation', models.CharField(blank=True, max_length=16, null=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=191, unique=True)),
                ('whatsapp', models.CharField(blank=True, max_length=32, null=True)),
                ('imc_registration_number', models.CharField(blank=True, max_length=64, null=True)),
                ('appointment_booking_number', models.CharField(blank=True, max_length=64, null=True)),
                ('clinic_address', models.TextField(blank=True, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('state', models.CharField(blank=True, max_length=64, null=True)),
                ('district', models.CharField(blank=True, max_length=64, null=True)),
                ('receptionist_whatsapp', models.CharField(blank=True, max_length=32, null=True)),
                ('photo_url', models.CharField(blank=True, max_length=512, null=True)),
                ('unique_doctor_code', models.CharField(max_length=32, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'registered_professionals',
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('option_code', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('display_order', models.IntegerField()),
                ('triggers_red_flag', models.BooleanField(default=False)),
                ('question', models.ForeignKey(db_column='question_code', on_delete=django.db.models.deletion.CASCADE, to='content.question')),
                ('red_flag', models.ForeignKey(blank=True, db_column='red_flag_code', null=True, on_delete=django.db.models.deletion.RESTRICT, to='content.redflag')),
            ],
            options={
                'db_table': 'options',
                'unique_together': {('question', 'display_order')},
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_code', models.CharField(max_length=32, unique=True)),
                ('flags_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email_to', models.CharField(max_length=191)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('sendgrid_message_id', models.CharField(blank=True, max_length=128, null=True)),
                ('lang', models.ForeignKey(db_column='lang_code', on_delete=django.db.models.deletion.RESTRICT, to='content.language')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='content.registeredprofessional')),
            ],
            options={
                'db_table': 'submissions',
            },
        ),
        migrations.CreateModel(
            name='OptionI18n',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=255)),
                ('lang', models.ForeignKey(db_column='lang_code', on_delete=django.db.models.deletion.RESTRICT, to='content.language')),
                ('option', models.ForeignKey(db_column='option_code', on_delete=django.db.models.deletion.CASCADE, to='content.option')),
            ],
            options={
                'db_table': 'options_i18n',
                'unique_together': {('option', 'lang')},
            },
        ),
        migrations.CreateModel(
            name='QuestionI18n',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('lang', models.ForeignKey(db_column='lang_code', on_delete=django.db.models.deletion.RESTRICT, to='content.language')),
                ('question', models.ForeignKey(db_column='question_code', on_delete=django.db.models.deletion.CASCADE, to='content.question')),
            ],
            options={
                'db_table': 'questions_i18n',
                'unique_together': {('question', 'lang')},
            },
        ),
        migrations.CreateModel(
            name='DoctorEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_markdown', models.TextField()),
                ('reference_1', models.CharField(blank=True, max_length=512, null=True)),
                ('reference_2', models.CharField(blank=True, max_length=512, null=True)),
                ('lang', models.ForeignKey(db_column='lang_code', on_delete=django.db.models.deletion.RESTRICT, to='content.language')),
                ('red_flag', models.ForeignKey(db_column='red_flag_code', on_delete=django.db.models.deletion.CASCADE, to='content.redflag')),
            ],
            options={
                'db_table': 'doctor_education',
                'unique_together': {('red_flag', 'lang')},
            },
        ),
        migrations.CreateModel(
            name='RedFlagI18n',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_label', models.CharField(max_length=255)),
                ('lang', models.ForeignKey(db_column='lang_code', on_delete=django.db.models.deletion.RESTRICT, to='content.language')),
                ('red_flag', models.ForeignKey(db_column='red_flag_code', on_delete=django.db.models.deletion.CASCADE, to='content.redflag')),
            ],
            options={
                'db_table': 'red_flags_i18n',
                'unique_together': {('red_flag', 'lang')},
            },
        ),
        migrations.CreateModel(
            name='ResultMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_code', models.CharField(max_length=64)),
                ('message_text', models.TextField()),
                ('lang', models.ForeignKey(db_column='lang_code', on_delete=django.db.models.deletion.RESTRICT, to='content.language')),
            ],
            options={
                'db_table': 'result_messages',
                'unique_together': {('message_code', 'lang')},
            },
        ),
        migrations.CreateModel(
            name='SubmissionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triggers_red_flag', models.BooleanField()),
                ('option', models.ForeignKey(db_column='option_code', on_delete=django.db.models.deletion.RESTRICT, to='content.option')),
                ('question', models.ForeignKey(db_column='question_code', on_delete=django.db.models.deletion.RESTRICT, to='content.question')),
                ('red_flag', models.ForeignKey(blank=True, db_column='red_flag_code', null=True, on_delete=django.db.models.deletion.RESTRICT, to='content.redflag')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.submission')),
            ],
            options={
                'db_table': 'submission_answers',
                'unique_together': {('submission', 'question')},
            },
        ),
        migrations.CreateModel(
            name='SubmissionRedFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('red_flag', models.ForeignKey(db_column='red_flag_code', on_delete=django.db.models.deletion.RESTRICT, to='content.redflag')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.submission')),
            ],
            options={
                'db_table': 'submission_red_flags',
                'unique_together': {('submission', 'red_flag')},
            },
        ),
        migrations.CreateModel(
            name='UiString',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64)),
                ('text', models.TextField()),
                ('lang', models.ForeignKey(db_column='lang_code', on_delete=django.db.models.deletion.RESTRICT, to='content.language')),
            ],
            options={
                'db_table': 'ui_strings',
                'unique_together': {('key', 'lang')},
            },
        ),
    ]
