# Generated by Django 5.2.6 on 2025-09-11 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeredprofessional',
            name='photo_url',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
