# Generated by Django 5.2.6 on 2025-09-24 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_registeredprofessional_photo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeredprofessional',
            name='terms_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registeredprofessional',
            name='terms_version',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
