# Generated by Django 5.2.6 on 2025-12-03 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_alter_submission_professional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='professional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='content.registeredprofessional'),
        ),
    ]
